export const SET_SELECTED_STOCK = "SET_SELECTED_STOCK";
export const FETCHING_STOCK = "FETCHING_STOCK";
export const UPDATE_STRATEGY_REPORTS = "UPDATE_STRATEGY_REPORTS";
export const FETCHING_STRATEGY_REPORTS = "FETCHING_STRATEGY_REPORTS";
export const SET_SELECTED_STRATEGY = "SET_SELECTED_STRATEGY";
export const SET_SELECTED_BACKTEST_RESULT = "SET_SELECTED_BACKTEST_RESULT";
export const UPDATE_STRATEGIES = "UPDATE_STRATEGIES";
export const FETCHING_STRATEGIES = "FETCHING_STRATEGIES";
export const SET_SELECTED_TRADE = "SET_SELECTED_TRADE";

