export const UPDATE_STRATEGY_REPORTS = "UPDATE_STRATEGY_REPORTS";
export const SET_SELECTED_STRATEGY = "SET_SELECTED_STRATEGY";
export const FETCHING_STRATEGY_REPORTS = "FETCHING_STRATEGY_REPORTS";
export const UPDATE_STRATEGIES = "UPDATE_STRATEGIES";
export const FETCHING_STRATEGIES = "FETCHING_STRATEGIES";